name: mental_health_nlp
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.10
  - graphviz
  - pip:
      - nltk==3.8.1
      - gensim==4.3.1
      - vaderSentiment==3.3.2
      - numpy==2.0.1
      - pandas==2.2.2
      - peft==0.12.0      
      - matplotlib==3.9.2
      - plotly==5.24.1
      - requests==2.32.3
      - rouge-score==0.1.2
      - scikit-learn==1.5.1
      - regex>=2022.10.31      
      - datasets>=2.14.4
      - huggingface-hub>=0.18.0
      - accelerate==0.31.0
      - graphviz==0.20.3
      - evaluate==0.4.2
      - joblib==1.4.2
      - loralib==0.1.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.44.0
      - notebook==7.2.1